title: Ajinkya Phanse
#logo: 
description: "ğŸš€ Master's in Data Science from Rutgers University, New Brunswick ğŸ“ | Former Accenture Data Analyst ğŸ’¼"
show_downloads: true
theme: jekyll-theme-minimal
